-- Highlight groups for imli.nvim
local M = {}

M.setup = function()
  local p = require("imli.palette").get()
  local italic_comments = require("imli").options.italic_comments
  local comment_opacity = math.max(0.1, math.min(1.0, require("imli").options.comment_opacity))
  local comment_fg = require("imli.palette").fade(p.comment, p.bg, 1 - comment_opacity)
  local hl = function(name, opts)
    vim.api.nvim_set_hl(0, name, opts)
  end

  -- Editor UI
  hl("Normal",       { fg = p.fg, bg = p.bg })
  hl("NormalFloat",  { fg = p.fg, bg = p.bg_alt })
  hl("FloatBorder",  { fg = p.border, bg = p.bg_alt, blend = 60 })
  hl("CursorLine",   { bg = p.bg_alt })
  hl("Visual",       { bg = p.selection })
  hl("LineNr",       { fg = p.fg_dim })
  hl("CursorLineNr", { fg = p.yellow, bold = true })
  hl("SignColumn",   { bg = p.bg })
  hl("StatusLine",   { fg = p.fg, bg = p.bg_alt })
  hl("StatusLineNC", {
    fg = require("imli.palette").fade(p.fg, p.bg_alt, 0.5),
    bg = require("imli.palette").fade(p.bg_alt, p.bg, 0.5),
  })
  hl("TabLine",     { fg = p.fg_dim, bg = p.bg_alt })
  hl("TabLineSel",  { fg = p.fg_dim, bg = "#132631", bold = true })
  hl("TabLineFill", { bg = p.bg })
  hl("VertSplit",    { fg = p.border })
  hl("WinSeparator", { fg = p.border })
  hl("Pmenu",        { fg = p.fg, bg = p.bg_alt })
  hl("PmenuSel",     { fg = p.fg, bg = p.selection, bold = true })
  hl("Search",       { fg = p.bg, bg = p.yellow })
  hl("IncSearch",    { fg = p.bg, bg = p.orange })
  hl("MatchParen",   { fg = p.orange, bold = true, underline = true })
  hl("Directory",    { fg = "#89A482" })
  hl("Title",        { fg = "#606676", bold = true })
  hl("FloatTitle",   { fg = "#606676", bold = true })
  hl("WinBar",       { fg = "#606676", bg = p.bg })
  hl("WinBarNC",     { fg = "#606676", bg = p.bg })

  -- Legacy syntax (still used by some filetypes)
  hl("Comment",     { fg = comment_fg, italic = italic_comments })
  hl("Constant",    { fg = p.orange })
  hl("String",      { fg = p.green })
  hl("Character",   { fg = p.green })
  hl("Number",      { fg = p.orange })
  hl("Boolean",     { fg = p.orange })
  hl("Float",       { fg = p.orange })
  hl("Identifier",  { fg = p.blue })
  hl("Function",    { fg = "#9564DD" })
  hl("Statement",   { fg = p.purple })
  hl("Conditional", { fg = p.purple })
  hl("Repeat",      { fg = p.purple })
  hl("Keyword",     { fg = p.purple })
  hl("Operator",    { fg = p.cyan })
  hl("PreProc",     { fg = p.magenta })
  hl("Type",        { fg = p.yellow })
  hl("Special",     { fg = p.cyan })
  hl("Error",       { fg = p.red, bold = true })
  hl("Todo",        { fg = p.yellow, bold = true })

  -- Treesitter captures
  hl("@comment",              { link = "Comment" })
  hl("@keyword",              { fg = p.purple, bold = true })
  hl("@keyword.return",       { fg = p.purple, bold = true })
  hl("@keyword.function",     { fg = p.purple })
  hl("@conditional",          { fg = p.purple })
  hl("@repeat",               { fg = p.purple })
  hl("@keyword.conditional",  { fg = p.purple })
  hl("@keyword.repeat",       { fg = p.purple })
  hl("@keyword.operator",     { fg = p.purple })
  hl("@keyword.import",       { fg = p.purple })
  hl("@keyword.modifier",     { fg = p.purple, italic = true })
  hl("@keyword.exception",    { fg = p.purple, bold = true })
  hl("@variable.member",      { fg = p.fg })
  hl("@punctuation.special",  { fg = p.cyan })
  hl("@string.special",       { fg = p.cyan })
  hl("@number.float",         { fg = p.orange })
  hl("@comment.todo",         { fg = p.yellow, bold = true })
  hl("@comment.error",        { fg = p.red, bold = true })
  hl("@comment.warning",      { fg = p.yellow, bold = true })
  hl("@comment.note",         { fg = p.blue, bold = true })
  hl("@function",             { fg = "#9564DD" })
  hl("@function.call",        { fg = "#9564DD" })
  hl("@function.builtin",     { fg = p.cyan })
  hl("@method",               { fg = "#9564DD" })
  hl("@method.call",          { fg = "#9564DD" })
  hl("@variable",             { fg = p.fg })
  hl("@variable.builtin",     { fg = p.red })
  hl("@parameter",            { fg = p.fg, italic = true })
  hl("@property",             { fg = p.fg })
  hl("@field",                { fg = p.fg })
  hl("@constant",             { fg = p.orange, bold = true })
  hl("@constant.builtin",     { fg = p.orange })
  hl("@string",               { fg = p.green })
  hl("@string.escape",        { fg = p.cyan })
  hl("@string.regexp",        { fg = p.orange })
  hl("@number",               { fg = p.orange })
  hl("@boolean",              { fg = p.orange })
  hl("@type",                 { fg = p.yellow })
  hl("@type.builtin",         { fg = p.yellow, italic = true })
  hl("@constructor",          { fg = p.yellow })
  hl("@operator",             { fg = p.cyan })
  hl("@punctuation.bracket",  { fg = p.fg_dim })
  hl("@punctuation.delimiter",{ fg = p.fg_dim })
  hl("@tag",                  { fg = p.red })
  hl("@tag.attribute",        { fg = p.yellow })
  hl("@attribute",            { fg = p.yellow })

  -- Markup (markdown etc.)
  hl("@markup.heading",        { fg = p.blue, bold = true })
  hl("@markup.heading.1",      { fg = p.red, bold = true })
  hl("@markup.heading.2",      { fg = p.orange, bold = true })
  hl("@markup.heading.3",      { fg = p.yellow, bold = true })
  hl("@markup.heading.4",      { fg = p.green, bold = true })
  hl("@markup.heading.5",      { fg = p.cyan, bold = true })
  hl("@markup.heading.6",      { fg = p.fg_dim, bold = true })
  hl("@markup.heading.4.markdown", { fg = p.green, bold = true })
  hl("@markup.heading.5.markdown", { fg = p.cyan, bold = true })
  hl("@markup.heading.6.markdown", { fg = p.fg_dim, bold = true })
  hl("@markup.list.unchecked", { fg = p.fg_dim })
  hl("@markup.list.checked",   { fg = p.green })
  hl("@markup.link.label.markdown_inline", { fg = p.cyan, underline = true })
  hl("@markup.link.markdown_inline",       { fg = p.blue, underline = true })
  hl("@label",                 { fg = p.cyan })
  hl("Label",                  { fg = p.cyan })
  hl("ColorColumn",            { bg = p.bg_alt })
  hl("RenderMarkdownCode",     { fg = p.green, bg = p.bg_alt })
  hl("RenderMarkdownCodeInline",{ fg = p.green, bg = p.bg_alt })
  hl("RenderMarkdownLink",     { fg = p.blue, underline = true })
  hl("RenderMarkdownQuote",    { fg = p.fg_dim, italic = italic_comments })
  hl("@markup.strong",         { fg = p.fg, bold = true })
  hl("@markup.italic",         { fg = p.fg, italic = true })
  hl("@markup.strikethrough",  { fg = p.fg_dim, strikethrough = true })
  hl("@markup.quote",          { fg = p.fg_dim, italic = true })
  hl("@markup.link",           { fg = p.blue, underline = true })
  hl("@markup.link.url",       { fg = p.cyan, underline = true })
  hl("@markup.raw",            { fg = p.green, bg = p.bg_alt })
  hl("@markup.list",           { fg = p.cyan })
  hl("@markup.math",           { fg = p.cyan })

  -- Diff
  hl("@diff.plus",   { fg = p.green })
  hl("@diff.minus",  { fg = p.red })
  hl("@diff.delta",  { fg = p.blue })
  hl("DiffAdd",      { bg = "#0f2a1e" })
  hl("DiffDelete",   { bg = "#33161a" })
  hl("DiffChange",   { bg = "#122530" })
  hl("DiffText",     { bg = "#1c3a4d" })

  -- LSP semantic tokens (override Treesitter defaults only where wanted)
  hl("@lsp.type.class",         { fg = p.yellow })
  hl("@lsp.type.interface",     { fg = p.yellow, italic = true })
  hl("@lsp.type.enum",          { fg = p.yellow })
  hl("@lsp.type.enumMember",    { fg = p.orange })
  hl("@lsp.type.struct",        { fg = p.yellow })
  hl("@lsp.type.type",          { fg = p.yellow })
  hl("@lsp.type.typeParameter", { fg = p.yellow, italic = true })
  hl("@lsp.type.parameter",     { fg = p.fg, italic = true })
  hl("@lsp.type.property",      { fg = p.fg })
  hl("@lsp.type.variable",      { fg = p.fg })
  hl("@lsp.type.namespace",     { fg = p.cyan })
  hl("@lsp.type.macro",         { fg = p.magenta })
  hl("@lsp.typemod.variable.readonly", { fg = p.orange, bold = true })
  hl("@lsp.mod.deprecated",     { fg = p.fg_dim, strikethrough = true })
  hl("@lsp.mod.async",          { fg = p.purple, italic = true })
  hl("@lsp.mod.defaultLibrary", { fg = p.cyan })

  -- LSP UI helpers
  hl("LspInlayHint",            { fg = p.fg_dim, bg = p.bg_alt, italic = true })
  hl("LspCodeLens",             { fg = p.fg_dim, italic = true })
  hl("LspCodeLensSeparator",    { fg = p.border })
  hl("LspReferenceText",        { bg = p.selection })
  hl("LspReferenceRead",        { bg = p.selection })
  hl("LspReferenceWrite",       { bg = p.selection, bold = true })
  hl("LspReferenceTarget",      { fg = p.orange, underline = true })
  hl("LspSignatureActiveParameter", { fg = p.orange, bold = true })

  -- which-key popup
  hl("WhichKey",      { fg = p.cyan })
  hl("WhichKeyDesc",  { fg = p.fg })
  hl("WhichKeyGroup", { fg = p.green })
  hl("WhichKeySeparator", { fg = p.comment, italic = italic_comments })
  hl("WhichKeyValue", { fg = p.comment })

  -- Mini.icons (icon colors in explorer/pickers)
  hl("MiniIconsAzure",  { fg = p.cyan })
  hl("MiniIconsBlue",   { fg = p.blue })
  hl("MiniIconsCyan",   { fg = p.cyan })
  hl("MiniIconsGreen",  { fg = p.green })
  hl("MiniIconsGrey",   { fg = p.fg_dim })
  hl("MiniIconsOrange", { fg = p.orange })
  hl("MiniIconsPurple", { fg = p.purple })
  hl("MiniIconsRed",    { fg = p.red })
  hl("MiniIconsYellow", { fg = p.yellow })

  -- mini.nvim: picker selection. MiniPmenuSelection is the group mini.pick,
  -- mini.grep, mini.hipatterns, ... use for the currently highlighted entry.
  hl("MiniPmenuSelection",         { fg = p.fg, bg = p.selection, bold = true })
  hl("MiniPmenuMatch",             { fg = p.orange, bold = true })
  hl("MiniPmenuMatchCurrent",      { fg = p.orange, bg = p.selection, bold = true })
  hl("MiniPmenuMatchMarked",       { fg = p.yellow, bold = true })
  hl("MiniPmenuMatchMarkedCurrent",{ fg = p.yellow, bg = p.selection, bold = true })
  hl("MiniPmenuMatchUnique",       { fg = p.purple, bold = true })
  hl("MiniPmenuExtra",             { fg = p.fg_dim })
  hl("MiniPmenuExtraMatch",        { fg = p.orange, bold = true })
  hl("MiniPickMatchCurrent",       { fg = p.orange, bg = p.selection, bold = true })
  hl("MiniCursorword",             { bg = p.selection })
  hl("MiniCursorwordCurrent",      { bg = p.bg_alt, bold = true })
  hl("MiniAnimateCursor",          { bg = p.selection })
  hl("MiniAnimateSelection",       { bg = p.selection })

  -- mini.nvim: explorer selection (mini.files / neo-tree style file pickers)
  hl("MiniFilesCursorLine",        { bg = p.selection, bold = true })
  hl("MiniFilesBorderSelected",    { fg = p.yellow, bold = true })
  hl("MiniFilesBorder",            { fg = p.border })
  hl("MiniFilesBorderModified",    { fg = p.orange })
  hl("MiniFilesDirectory",         { fg = p.blue })
  hl("MiniFilesFile",              { fg = p.fg })
  hl("MiniFilesFileModified",      { fg = p.orange })
  hl("MiniFilesNormal",            { fg = p.fg_dim })
  hl("MiniFilesTitleFocused",      { fg = p.yellow, bold = true })
  hl("MiniFilesTitleUnfocused",    { fg = p.fg_dim })
  hl("MiniPickBorder",             { fg = p.border })
  hl("MiniPickBorderBusy",         { fg = p.yellow })
  hl("MiniPickBorderTextFocused",  { fg = p.yellow, bold = true })
  hl("MiniPickBorderTextTitleFocused", { fg = p.blue, bg = p.bg_alt, bold = true })
  hl("MiniPickHeader",             { fg = p.fg_dim, bg = p.bg_alt })
  hl("MiniPickHeaderPrefix",       { fg = p.cyan, bg = p.bg_alt })
  hl("MiniPickHeaderSecondary",    { fg = p.fg_dim, bg = p.bg_alt })
  hl("MiniStarterCurrent",         { fg = p.fg, bg = p.selection, bold = true })
  hl("MiniStarterItem",            { fg = p.fg })
  hl("MiniStarterSection",         { fg = p.blue })
  hl("MiniStarterFooter",          { fg = p.fg_dim })
  hl("MiniStarterHeader",          { fg = p.purple, italic = italic_comments })
  hl("MiniStarterInactive",        { fg = p.fg_dim })
  hl("MiniStarterItemBullet",      { fg = p.fg_dim })
  hl("MiniStarterItemPrefix",      { fg = p.orange })
  hl("MiniStarterQuery",           { fg = p.cyan })
  hl("MiniTablineCurrent",         { fg = p.fg, bg = p.selection, bold = true })
  hl("MiniTablineVisible",         { fg = p.fg_dim, bg = p.bg_alt })
  hl("MiniTablineHidden",          { fg = p.fg_dim, bg = p.bg })
  hl("MiniTablineFill",            { bg = p.bg })
  hl("MiniTablineModifiedCurrent", { fg = p.orange, bg = p.selection, bold = true })
  hl("MiniTablineModifiedVisible", { fg = p.orange, bg = p.bg_alt })
  hl("MiniTablineModifiedHidden",  { fg = p.orange, bg = p.bg })
  hl("MiniTablineTabpagesection",  { fg = p.purple, bg = p.bg })

  -- Transparent background: clears the 'bg' of editor background groups so
  -- the terminal's background shows through.
  if require("imli").options.transparent_bg then
    local bg_groups = {
      "Normal", "NormalFloat", "FloatBorder", "CursorLine", "SignColumn",
      "StatusLine", "StatusLineNC", "TabLine", "TabLineFill", "WinBar",
      "WinBarNC", "ColorColumn", "Pmenu", "PmenuSel",
      "DiagnosticVirtualTextError", "DiagnosticVirtualTextWarn",
      "DiagnosticVirtualTextInfo", "DiagnosticVirtualTextHint",
      "MiniTablineFill", "MiniTablineHidden", "MiniTablineVisible",
    }
    for _, name in ipairs(bg_groups) do
      local def = vim.api.nvim_get_hl(0, { name = name, link = false })
      def.bg = "none"
      hl(name, def)
    end
  end

  -- Diagnostics
  hl("DiagnosticError", { fg = p.red })
  hl("DiagnosticWarn",  { fg = p.yellow })
  hl("DiagnosticInfo",  { fg = p.blue })
  hl("DiagnosticHint",  { fg = p.cyan })
  hl("DiagnosticUnderlineError", { undercurl = true, sp = p.red })
  hl("DiagnosticUnderlineWarn",  { undercurl = true, sp = p.yellow })
  hl("DiagnosticUnderlineInfo",  { undercurl = true, sp = p.blue })
  hl("DiagnosticUnderlineHint",  { undercurl = true, sp = p.cyan })
  hl("DiagnosticVirtualTextError", { fg = p.red, bg = p.bg_alt })
  hl("DiagnosticVirtualTextWarn",  { fg = p.yellow, bg = p.bg_alt })
  hl("DiagnosticVirtualTextInfo",  { fg = p.blue, bg = p.bg_alt })
  hl("DiagnosticVirtualTextHint",  { fg = p.cyan, bg = p.bg_alt })
end

return M
